### ISSUE TITLE
Cgroups.Apply方法无法生效

### ISSUE THREAD

**Issue by ryanwuer** [wilhelmguo/gocker#2]
Cgroups.Apply方法代码
https://github.com/wilhelmguo/gocker/blob/b01d7f2e1a95a128b6f547f4cd6d485222dbdf26/cgroups/cgoups.go#L25-L47

Apply之前未将命令行参数中的cpu和memory设置为对象cgroup的成员变量
https://github.com/wilhelmguo/gocker/blob/b01d7f2e1a95a128b6f547f4cd6d485222dbdf26/runc/run.go#L76-L87

已提PR尝试解决： #1

**Comment by wilhelmguo** [comment]
已经合并了，谢谢 PR
